[build]
  base = 'Frontend'
  command = 'CI= npm run build'

[[redirects]]
  from = "/resetpassword?token=:guid"
  to = "/resetpassword?token=:guid"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200